
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package Dasm;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 19;
  public static final int End = 11;
  public static final int oval = 42;
  public static final int line = 43;
  public static final int decim = 23;
  public static final int string = 44;
  public static final int set_global = 37;
  public static final int F = 33;
  public static final int Br = 26;
  public static final int D = 32;
  public static final int Lte = 16;
  public static final int Pot = 6;
  public static final int C = 31;
  public static final int tee_global = 39;
  public static final int tee_local = 38;
  public static final int Br_if = 24;
  public static final int Diff = 3;
  public static final int quadrate = 41;
  public static final int EOF = 0;
  public static final int Br__if = 25;
  public static final int Not = 20;
  public static final int Function = 10;
  public static final int And = 18;
  public static final int error = 1;
  public static final int MENOS = 30;
  public static final int Gt = 15;
  public static final int Div = 5;
  public static final int Print = 27;
  public static final int point = 40;
  public static final int id = 21;
  public static final int get_global = 36;
  public static final int Mul = 4;
  public static final int Add = 2;
  public static final int Mod = 7;
  public static final int DPUNTOS = 29;
  public static final int Eqz = 12;
  public static final int Gte = 17;
  public static final int get_local = 34;
  public static final int Call = 8;
  public static final int enter = 22;
  public static final int Eqs = 13;
  public static final int DOLAR = 28;
  public static final int set_local = 35;
  public static final int Lt = 14;
  public static final int Calc = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Add",
  "Diff",
  "Mul",
  "Div",
  "Pot",
  "Mod",
  "Call",
  "Calc",
  "Function",
  "End",
  "Eqz",
  "Eqs",
  "Lt",
  "Gt",
  "Lte",
  "Gte",
  "And",
  "Or",
  "Not",
  "id",
  "enter",
  "decim",
  "Br_if",
  "Br__if",
  "Br",
  "Print",
  "DOLAR",
  "DPUNTOS",
  "MENOS",
  "C",
  "D",
  "F",
  "get_local",
  "set_local",
  "get_global",
  "set_global",
  "tee_local",
  "tee_global",
  "point",
  "quadrate",
  "oval",
  "line",
  "string"
  };
}

