
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package Dplusplus;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int continuar = 52;
  public static final int bool = 15;
  public static final int POT = 32;
  public static final int PREG = 39;
  public static final int POR = 31;
  public static final int imprimir = 54;
  public static final int DIFERENTE = 46;
  public static final int detener = 51;
  public static final int nulo = 8;
  public static final int decim = 14;
  public static final int NOT = 37;
  public static final int AND = 36;
  public static final int IGUAL = 45;
  public static final int caracter = 5;
  public static final int struct = 11;
  public static final int OR = 35;
  public static final int si = 47;
  public static final int mientras = 50;
  public static final int INC = 33;
  public static final int DIV = 30;
  public static final int ovalo = 57;
  public static final int LLAV_C = 21;
  public static final int LLAV_A = 20;
  public static final int PYCOMA = 27;
  public static final int EOF = 0;
  public static final int ASIG = 38;
  public static final int cuadrado = 56;
  public static final int para = 49;
  public static final int MAYOR_I = 43;
  public static final int error = 1;
  public static final int COMA = 24;
  public static final int MENOS = 29;
  public static final int MENOR = 42;
  public static final int entero = 2;
  public static final int PAR_C = 19;
  public static final int MENOR_I = 44;
  public static final int PAR_A = 18;
  public static final int punto = 55;
  public static final int impor = 10;
  public static final int vacio = 7;
  public static final int MAYOR = 41;
  public static final int id = 12;
  public static final int PUNTO = 26;
  public static final int linea = 58;
  public static final int cad = 17;
  public static final int carac = 16;
  public static final int booleano = 4;
  public static final int DPUNTOS = 25;
  public static final int retornar = 53;
  public static final int COR_C = 23;
  public static final int DEC = 34;
  public static final int COR_A = 22;
  public static final int ARK = 40;
  public static final int enter = 13;
  public static final int principal = 9;
  public static final int decimal = 3;
  public static final int sino = 48;
  public static final int cadena = 6;
  public static final int MAS = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "entero",
  "decimal",
  "booleano",
  "caracter",
  "cadena",
  "vacio",
  "nulo",
  "principal",
  "impor",
  "struct",
  "id",
  "enter",
  "decim",
  "bool",
  "carac",
  "cad",
  "PAR_A",
  "PAR_C",
  "LLAV_A",
  "LLAV_C",
  "COR_A",
  "COR_C",
  "COMA",
  "DPUNTOS",
  "PUNTO",
  "PYCOMA",
  "MAS",
  "MENOS",
  "DIV",
  "POR",
  "POT",
  "INC",
  "DEC",
  "OR",
  "AND",
  "NOT",
  "ASIG",
  "PREG",
  "ARK",
  "MAYOR",
  "MENOR",
  "MAYOR_I",
  "MENOR_I",
  "IGUAL",
  "DIFERENTE",
  "si",
  "sino",
  "para",
  "mientras",
  "detener",
  "continuar",
  "retornar",
  "imprimir",
  "punto",
  "cuadrado",
  "ovalo",
  "linea"
  };
}

