
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package DracoScript;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int bool = 7;
  public static final int POT = 20;
  public static final int POR = 19;
  public static final int imprimir = 40;
  public static final int DIFERENTE = 33;
  public static final int detener = 39;
  public static final int nulo = 3;
  public static final int sinosi = 36;
  public static final int NOT = 25;
  public static final int AND = 24;
  public static final int IGUAL = 32;
  public static final int OR = 23;
  public static final int si = 34;
  public static final int mientras = 38;
  public static final int INC = 21;
  public static final int DIV = 18;
  public static final int ovalo = 43;
  public static final int LLAV_C = 13;
  public static final int run = 4;
  public static final int LLAV_A = 12;
  public static final int var = 2;
  public static final int PYCOMA = 15;
  public static final int EOF = 0;
  public static final int ASIG = 26;
  public static final int cuadrado = 42;
  public static final int para = 37;
  public static final int error = 1;
  public static final int MAYOR_I = 30;
  public static final int COMA = 14;
  public static final int si_no = 35;
  public static final int MENOS = 17;
  public static final int MENOR = 29;
  public static final int PAR_C = 11;
  public static final int MOD = 27;
  public static final int MENOR_I = 31;
  public static final int PAR_A = 10;
  public static final int punto = 41;
  public static final int MAYOR = 28;
  public static final int id = 5;
  public static final int linea = 44;
  public static final int cad = 9;
  public static final int carac = 8;
  public static final int DEC = 22;
  public static final int cadena = 45;
  public static final int number = 6;
  public static final int MAS = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "var",
  "nulo",
  "run",
  "id",
  "number",
  "bool",
  "carac",
  "cad",
  "PAR_A",
  "PAR_C",
  "LLAV_A",
  "LLAV_C",
  "COMA",
  "PYCOMA",
  "MAS",
  "MENOS",
  "DIV",
  "POR",
  "POT",
  "INC",
  "DEC",
  "OR",
  "AND",
  "NOT",
  "ASIG",
  "MOD",
  "MAYOR",
  "MENOR",
  "MAYOR_I",
  "MENOR_I",
  "IGUAL",
  "DIFERENTE",
  "si",
  "si_no",
  "sinosi",
  "para",
  "mientras",
  "detener",
  "imprimir",
  "punto",
  "cuadrado",
  "ovalo",
  "linea",
  "cadena"
  };
}

